#ifndef FILEPROTECT_IOCTL_H
#define FILEPROTECT_IOCTL_H

// 设备类型
#define FILEPROTECT_DEVICE_TYPE 0x800F

// 符号链接名（用户态通过 \\.\FileProtectFS 访问）
#define FILEPROTECT_SYMLINK_NAME L"\\DosDevices\\FileProtectFS"
#define FILEPROTECT_WIN32_NAME  L"\\\\.\\FileProtectFS"

// IOCTL 码 — 使用 METHOD_BUFFERED 简化缓冲区管理
#define IOCTL_FILEPROTECT_ADD_FILE \
    CTL_CODE(FILEPROTECT_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_FILEPROTECT_REMOVE_FILE \
    CTL_CODE(FILEPROTECT_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_FILEPROTECT_CLEAR_ALL \
    CTL_CODE(FILEPROTECT_DEVICE_TYPE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_FILEPROTECT_QUERY_LIST \
    CTL_CODE(FILEPROTECT_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_FILEPROTECT_GET_COUNT \
    CTL_CODE(FILEPROTECT_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

// 文件路径最大长度 (UTF-16 字符数)
#define FILEPROTECT_MAX_PATH 1024

// IOCTL 缓冲区结构体
typedef struct _FILEPROTECT_IOCTL_BUFFER {
    WCHAR FilePath[FILEPROTECT_MAX_PATH];
} FILEPROTECT_IOCTL_BUFFER, *PFILEPROTECT_IOCTL_BUFFER;

// 查询返回的条目结构
typedef struct _FILEPROTECT_QUERY_ENTRY {
    WCHAR FilePath[FILEPROTECT_MAX_PATH];
    LARGE_INTEGER AddTime;
} FILEPROTECT_QUERY_ENTRY, *PFILEPROTECT_QUERY_ENTRY;

#endif // FILEPROTECT_IOCTL_H
